import ROOT as r

#f = r.TFile.Open("/uboone/data/users/cerati/fittedVertexNtuple_bnb_pandoraNuKalmanTrack_v06_48_00_v2.root","READ")
#f = r.TFile.Open("/uboone/data/users/cerati/fittedvertexntuplewithinput_bnb_cosmics_mcc8.3_reco2.root","READ")
#f = r.TFile.Open("/pnfs/uboone/scratch/users/cerati/mcc8.3/v06_54_00/ntuple/fittedvertexntuplewithinput_bnb_cosmics_mcc8.3_reco2/662911_143/dummyAnalysis-pf.root","READ")
#f = r.TFile.Open("/pnfs/uboone/scratch/users/cerati/mcc8.3/v06_54_00/ntuple/fittedvertexntuplewithinput_bnb_cosmics_mcc8.3_reco2/664156_573/dummyAnalysis-pf.root","READ")
#f = r.TFile.Open("/pnfs/uboone/scratch/users/cerati/mcc8.3/v06_54_00/ntuple/fittedvertexntuplewithinput_bnb_cosmics_mcc8.3_reco2/664524_658/dummyAnalysis-pf.root","READ")
#f = r.TFile.Open("dummyAnalysis-pf.root","READ")
#f = r.TFile.Open("/pnfs/uboone/scratch/users/cerati/mcc8.3/v06_54_00/ntuple/fittedvertexntuplewithinput_bnb_cosmics_mcc8.3_reco2/687269_687/dummyAnalysis-pf.root","READ")
#f = r.TFile.Open("/uboone/data/users/cerati/fittedvertexntuplewithinput_bnb_nu_cosmic_mcc8.3_reco2_sipcut.root","READ")
#f = r.TFile.Open("/uboone/data/users/cerati/fittedvertexntuplewithinput_bnb_nu_mcc8.1_reco2_sipcut.root","READ")
#f = r.TFile.Open("dummyAnalysis-pf-bnbcos-sipcut3.root","READ")
#f = r.TFile.Open("dummyAnalysis-pf-bnbcos-sipcut3-mind.root","READ")
#f = r.TFile.Open("dummyAnalysis-pf-bnbcos-sipcut3-invtx.root","READ")

f = r.TFile.Open("/uboone/data/users/cerati/fittedvertexntuplewithinput_bnb_nu_cosmic_mcc8.4_reco2_sipcut_v3.root","READ")

t0 = f.Get("fittedvertexntuplizer/tree")

#t1 = f.Get("fittedvertexntuplizer/tree")
t1 = f.Get("fittedvertexntuplizerinputs/tree")

xresfitold = r.TH1F("xresfitold","xresfitold",100,-1,1)
yresfitold = r.TH1F("yresfitold","yresfitold",100,-1,1)
zresfitold = r.TH1F("zresfitold","zresfitold",100,-1,1)
t0.Draw("(vtx_fit_x - vtx_gen_x)>>xresfitold","","goff")
t0.Draw("(vtx_fit_y - vtx_gen_y)>>yresfitold","","goff")
t0.Draw("(vtx_fit_z - vtx_gen_z)>>zresfitold","","goff")
xresfit = r.TH1F("xresfit","xresfit",100,-1,1)
yresfit = r.TH1F("yresfit","yresfit",100,-1,1)
zresfit = r.TH1F("zresfit","zresfit",100,-1,1)
t1.Draw("(vtx_fit_x - vtx_gen_x)>>xresfit","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y)>>yresfit","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z)>>zresfit","","goff")
xrespan = r.TH1F("xrespan","xrespan",100,-1,1)
yrespan = r.TH1F("yrespan","yrespan",100,-1,1)
zrespan = r.TH1F("zrespan","zrespan",100,-1,1)
t1.Draw("(vtx_pan_x - vtx_gen_x)>>xrespan","","goff")
t1.Draw("(vtx_pan_y - vtx_gen_y)>>yrespan","","goff")
t1.Draw("(vtx_pan_z - vtx_gen_z)>>zrespan","","goff")
xresfitold.SetLineColor(r.kBlue)
yresfitold.SetLineColor(r.kBlue)
zresfitold.SetLineColor(r.kBlue)
xrespan.SetLineColor(r.kRed)
yrespan.SetLineColor(r.kRed)
zrespan.SetLineColor(r.kRed)
r.gStyle.SetOptStat(0)
c1 = r.TCanvas("c1","c1",1800,600)
c1.Divide(3,1)
c1.cd(1)
xresfit.SetTitle("")
xresfit.GetXaxis().SetTitle("#Deltax [cm]")
xresfit.Draw()
xrespan.Draw("same")
xresfitold.Draw("same")
c1.cd(2)
yresfit.SetTitle("")
yresfit.GetXaxis().SetTitle("#Deltay [cm]")
yresfit.Draw()
yrespan.Draw("same")
yresfitold.Draw("same")
c1.cd(3)
zresfit.SetTitle("")
zresfit.GetXaxis().SetTitle("#Deltaz [cm]")
zresfit.Draw()
zrespan.Draw("same")
zresfitold.Draw("same")
c1.SaveAs("c1.png")

xpull = r.TH1F("xpull","xpull",100,-5,5)
ypull = r.TH1F("ypull","ypull",100,-5,5)
zpull = r.TH1F("zpull","zpull",100,-5,5)
t1.Draw("(vtx_fit_x - vtx_gen_x)/sqrt(vtx_fit_cxx)>>xpull","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y)/sqrt(vtx_fit_cyy)>>ypull","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z)/sqrt(vtx_fit_czz)>>zpull","","goff")
c2 = r.TCanvas("c2","c2",1800,600)
c2.Divide(3,1)
c2.cd(1)
xpull.SetTitle("")
xpull.GetXaxis().SetTitle("#Deltax/#sigma_{x}")
xpull.Draw()
xpull.Fit("gaus","","",-1,3)
c2.cd(2)
ypull.SetTitle("")
ypull.GetXaxis().SetTitle("#Deltay/#sigma_{y}")
ypull.Draw()
ypull.Fit("gaus","","",-2,2)
c2.cd(3)
zpull.SetTitle("")
zpull.GetXaxis().SetTitle("#Deltaz/#sigma_{z}")
zpull.Draw()
zpull.Fit("gaus","","",-2,2)
c2.SaveAs("c2.png")

xresfitvschi2 = r.TH2F("xresfitvschi2","xresfitvschi2",20,0,50,100,-2,2)
yresfitvschi2 = r.TH2F("yresfitvschi2","yresfitvschi2",20,0,50,100,-2,2)
zresfitvschi2 = r.TH2F("zresfitvschi2","zresfitvschi2",20,0,50,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_chi2/vtx_fit_ndof)>>xresfitvschi2","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_chi2/vtx_fit_ndof)>>yresfitvschi2","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_chi2/vtx_fit_ndof)>>zresfitvschi2","","goff")
c3 = r.TCanvas("c3","c3",1800,600)
c3.Divide(3,1)
c3.cd(1)
xresfitvschi2.FitSlicesY()
xresfitvschi2_2 = r.gDirectory.Get("xresfitvschi2_2")
xresfitvschi2_2.SetTitle("")
xresfitvschi2_2.GetYaxis().SetTitleOffset(1.4)
xresfitvschi2_2.GetYaxis().SetRangeUser(0,2)
xresfitvschi2_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
xresfitvschi2_2.GetXaxis().SetTitle("#chi^{2}/ndof")
xresfitvschi2_2.Draw("")
c3.cd(2)
yresfitvschi2.FitSlicesY()
yresfitvschi2_2 = r.gDirectory.Get("yresfitvschi2_2")
yresfitvschi2_2.SetTitle("")
yresfitvschi2_2.GetYaxis().SetTitleOffset(1.4)
yresfitvschi2_2.GetYaxis().SetRangeUser(0,2)
yresfitvschi2_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
yresfitvschi2_2.GetXaxis().SetTitle("#chi^{2}/ndof")
yresfitvschi2_2.Draw("")
c3.cd(3)
zresfitvschi2.FitSlicesY()
zresfitvschi2_2 = r.gDirectory.Get("zresfitvschi2_2")
zresfitvschi2_2.SetTitle("")
zresfitvschi2_2.GetYaxis().SetTitleOffset(1.4)
zresfitvschi2_2.GetYaxis().SetRangeUser(0,2)
zresfitvschi2_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
zresfitvschi2_2.GetXaxis().SetTitle("#chi^{2}/ndof")
zresfitvschi2_2.Draw("")
c3.SaveAs("c3.png")

xresfitvsmaxd = r.TH2F("xresfitvsmaxd","xresfitvsmaxd",20,-5,5,100,-2,2)
yresfitvsmaxd = r.TH2F("yresfitvsmaxd","yresfitvsmaxd",20,-5,5,100,-2,2)
zresfitvsmaxd = r.TH2F("zresfitvsmaxd","zresfitvsmaxd",20,-5,5,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_tkdists_max)>>xresfitvsmaxd","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_tkdists_max)>>yresfitvsmaxd","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_tkdists_max)>>zresfitvsmaxd","","goff")
c4 = r.TCanvas("c4","c4",1800,600)
c4.Divide(3,1)
c4.cd(1)
xresfitvsmaxd.FitSlicesY()
xresfitvsmaxd_2 = r.gDirectory.Get("xresfitvsmaxd_2")
xresfitvsmaxd_2.SetTitle("")
xresfitvsmaxd_2.GetYaxis().SetTitleOffset(1.4)
xresfitvsmaxd_2.GetYaxis().SetRangeUser(0,2)
xresfitvsmaxd_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
xresfitvsmaxd_2.GetXaxis().SetTitle("max prop dist [cm]")
xresfitvsmaxd_2.Draw("")
c4.cd(2)
yresfitvsmaxd.FitSlicesY()
yresfitvsmaxd_2 = r.gDirectory.Get("yresfitvsmaxd_2")
yresfitvsmaxd_2.SetTitle("")
yresfitvsmaxd_2.GetYaxis().SetTitleOffset(1.4)
yresfitvsmaxd_2.GetYaxis().SetRangeUser(0,2)
yresfitvsmaxd_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
yresfitvsmaxd_2.GetXaxis().SetTitle("max prop dist [cm]")
yresfitvsmaxd_2.Draw("")
c4.cd(3)
zresfitvsmaxd.FitSlicesY()
zresfitvsmaxd_2 = r.gDirectory.Get("zresfitvsmaxd_2")
zresfitvsmaxd_2.SetTitle("")
zresfitvsmaxd_2.GetYaxis().SetTitleOffset(1.4)
zresfitvsmaxd_2.GetYaxis().SetRangeUser(0,2)
zresfitvsmaxd_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
zresfitvsmaxd_2.GetXaxis().SetTitle("max prop dist [cm]")
zresfitvsmaxd_2.Draw("")
c4.SaveAs("c4.png")

xresfitnocut = r.TH1F("xresfitnocut","xresfitnocut",100,-1,1)
yresfitnocut = r.TH1F("yresfitnocut","yresfitnocut",100,-1,1)
zresfitnocut = r.TH1F("zresfitnocut","zresfitnocut",100,-1,1)
t1.Draw("(vtx_fit_x - vtx_gen_x)>>xresfitnocut","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y)>>yresfitnocut","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z)>>zresfitnocut","","goff")
c5 = r.TCanvas("c5","c5",1800,600)
c5.Divide(3,1)
c5.cd(1)
xresfitnocut.SetTitle("")
xresfitnocut.GetXaxis().SetTitle("#Deltax [cm]")
xresfitnocut.Draw()
xresfitnocut.Fit("gaus","","",-0.2,0.2)
c5.cd(2)
yresfitnocut.SetTitle("")
yresfitnocut.GetXaxis().SetTitle("#Deltay [cm]")
yresfitnocut.Draw()
yresfitnocut.Fit("gaus","","",-0.2,0.2)
c5.cd(3)
zresfitnocut.SetTitle("")
zresfitnocut.GetXaxis().SetTitle("#Deltaz [cm]")
zresfitnocut.Draw()
zresfitnocut.Fit("gaus","","",-0.2,0.2)
c5.SaveAs("c5.png")

xrespannocut = r.TH1F("xrespannocut","xrespannocut",100,-1,1)
yrespannocut = r.TH1F("yrespannocut","yrespannocut",100,-1,1)
zrespannocut = r.TH1F("zrespannocut","zrespannocut",100,-1,1)
t1.Draw("(vtx_pan_x - vtx_gen_x)>>xrespannocut","","goff")
t1.Draw("(vtx_pan_y - vtx_gen_y)>>yrespannocut","","goff")
t1.Draw("(vtx_pan_z - vtx_gen_z)>>zrespannocut","","goff")
xrespannocut.SetLineColor(r.kRed)
yrespannocut.SetLineColor(r.kRed)
zrespannocut.SetLineColor(r.kRed)
c5p = r.TCanvas("c5p","c5p",1800,600)
c5p.Divide(3,1)
c5p.cd(1)
xrespannocut.SetTitle("")
xrespannocut.GetXaxis().SetTitle("#Deltax [cm]")
xrespannocut.Draw()
xrespannocut.Fit("gaus","","",-0.2,0.2)
c5p.cd(2)
yrespannocut.SetTitle("")
yrespannocut.GetXaxis().SetTitle("#Deltay [cm]")
yrespannocut.Draw()
yrespannocut.Fit("gaus","","",-0.2,0.2)
c5p.cd(3)
zrespannocut.SetTitle("")
zrespannocut.GetXaxis().SetTitle("#Deltaz [cm]")
zrespannocut.Draw()
zrespannocut.Fit("gaus","","",-0.2,0.2)
c5p.SaveAs("c5p.png")

xresfityescut = r.TH1F("xresfityescut","xresfityescut",100,-1,1)
yresfityescut = r.TH1F("yresfityescut","yresfityescut",100,-1,1)
zresfityescut = r.TH1F("zresfityescut","zresfityescut",100,-1,1)
t1.Draw("(vtx_fit_x - vtx_gen_x)>>xresfityescut","vtx_fit_tkdists_max>-2 && vtx_fit_tkdists_max<0.5 && (vtx_fit_chi2/vtx_fit_ndof)<5","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y)>>yresfityescut","vtx_fit_tkdists_max>-2 && vtx_fit_tkdists_max<0.5 && (vtx_fit_chi2/vtx_fit_ndof)<5","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z)>>zresfityescut","vtx_fit_tkdists_max>-2 && vtx_fit_tkdists_max<0.5 && (vtx_fit_chi2/vtx_fit_ndof)<5","goff")
c6 = r.TCanvas("c6","c6",1800,600)
c6.Divide(3,1)
c6.cd(1)
xresfityescut.SetTitle("")
xresfityescut.GetXaxis().SetTitle("#Deltax [cm]")
xresfityescut.Draw()
xresfityescut.Fit("gaus","","",-0.2,0.2)
c6.cd(2)
yresfityescut.SetTitle("")
yresfityescut.GetXaxis().SetTitle("#Deltay [cm]")
yresfityescut.Draw()
yresfityescut.Fit("gaus","","",-0.2,0.2)
c6.cd(3)
zresfityescut.SetTitle("")
zresfityescut.GetXaxis().SetTitle("#Deltaz [cm]")
zresfityescut.Draw()
zresfityescut.Fit("gaus","","",-0.2,0.2)
c6.SaveAs("c6.png")

xresfitvsntks = r.TH2F("xresfitvsntks","xresfitvsntks",4,2,5,100,-2,2)
yresfitvsntks = r.TH2F("yresfitvsntks","yresfitvsntks",4,2,5,100,-2,2)
zresfitvsntks = r.TH2F("zresfitvsntks","zresfitvsntks",4,2,5,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_ntks)>>xresfitvsntks","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_ntks)>>yresfitvsntks","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_ntks)>>zresfitvsntks","","goff")
c7 = r.TCanvas("c7","c7",1800,600)
c7.Divide(3,1)
c7.cd(1)
xresfitvsntks.FitSlicesY()
xresfitvsntks_2 = r.gDirectory.Get("xresfitvsntks_2")
xresfitvsntks_2.SetTitle("")
xresfitvsntks_2.GetYaxis().SetTitleOffset(1.4)
xresfitvsntks_2.GetYaxis().SetRangeUser(0,2)
xresfitvsntks_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
xresfitvsntks_2.GetXaxis().SetTitle("number of tracks")
xresfitvsntks_2.Draw("")
c7.cd(2)
yresfitvsntks.FitSlicesY()
yresfitvsntks_2 = r.gDirectory.Get("yresfitvsntks_2")
yresfitvsntks_2.SetTitle("")
yresfitvsntks_2.GetYaxis().SetTitleOffset(1.4)
yresfitvsntks_2.GetYaxis().SetRangeUser(0,2)
yresfitvsntks_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
yresfitvsntks_2.GetXaxis().SetTitle("number of tracks")
yresfitvsntks_2.Draw("")
c7.cd(3)
zresfitvsntks.FitSlicesY()
zresfitvsntks_2 = r.gDirectory.Get("zresfitvsntks_2")
zresfitvsntks_2.SetTitle("")
zresfitvsntks_2.GetYaxis().SetTitleOffset(1.4)
zresfitvsntks_2.GetYaxis().SetRangeUser(0,2)
zresfitvsntks_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
zresfitvsntks_2.GetXaxis().SetTitle("number of tracks")
zresfitvsntks_2.Draw("")
c7.SaveAs("c7.png")

xresfitvsmaxip = r.TH2F("xresfitvsmaxip","xresfitvsmaxip",20,0,10,100,-2,2)
yresfitvsmaxip = r.TH2F("yresfitvsmaxip","yresfitvsmaxip",20,0,10,100,-2,2)
zresfitvsmaxip = r.TH2F("zresfitvsmaxip","zresfitvsmaxip",20,0,10,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_tkubip_max)>>xresfitvsmaxip","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_tkubip_max)>>yresfitvsmaxip","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_tkubip_max)>>zresfitvsmaxip","","goff")
c8 = r.TCanvas("c8","c8",1800,600)
c8.Divide(3,1)
c8.cd(1)
#xresfitvsmaxip.FitSlicesY()
#xresfitvsmaxip_2 = r.gDirectory.Get("xresfitvsmaxip_2")
#xresfitvsmaxip_2.SetTitle("")
#xresfitvsmaxip_2.GetYaxis().SetTitleOffset(1.4)
#xresfitvsmaxip_2.GetYaxis().SetRangeUser(0,2)
#xresfitvsmaxip_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
#xresfitvsmaxip_2.GetXaxis().SetTitle("max ip")
#xresfitvsmaxip_2.Draw("")
xresfitvsmaxip.Draw("colz")
c8.cd(2)
#yresfitvsmaxip.FitSlicesY()
#yresfitvsmaxip_2 = r.gDirectory.Get("yresfitvsmaxip_2")
#yresfitvsmaxip_2.SetTitle("")
#yresfitvsmaxip_2.GetYaxis().SetTitleOffset(1.4)
#yresfitvsmaxip_2.GetYaxis().SetRangeUser(0,2)
#yresfitvsmaxip_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
#yresfitvsmaxip_2.GetXaxis().SetTitle("max ip")
#yresfitvsmaxip_2.Draw("")
yresfitvsmaxip.Draw("colz")
c8.cd(3)
#zresfitvsmaxip.FitSlicesY()
#zresfitvsmaxip_2 = r.gDirectory.Get("zresfitvsmaxip_2")
#zresfitvsmaxip_2.SetTitle("")
#zresfitvsmaxip_2.GetYaxis().SetTitleOffset(1.4)
#zresfitvsmaxip_2.GetYaxis().SetRangeUser(0,2)
#zresfitvsmaxip_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
#zresfitvsmaxip_2.GetXaxis().SetTitle("max ip")
#zresfitvsmaxip_2.Draw("")
zresfitvsmaxip.Draw("colz")
c8.SaveAs("c8.png")

xresfitvsmaxsip = r.TH2F("xresfitvsmaxsip","xresfitvsmaxsip",20,0,10,100,-2,2)
yresfitvsmaxsip = r.TH2F("yresfitvsmaxsip","yresfitvsmaxsip",20,0,10,100,-2,2)
zresfitvsmaxsip = r.TH2F("zresfitvsmaxsip","zresfitvsmaxsip",20,0,10,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_tkubsip_max)>>xresfitvsmaxsip","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_tkubsip_max)>>yresfitvsmaxsip","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_tkubsip_max)>>zresfitvsmaxsip","","goff")
c9 = r.TCanvas("c9","c9",1800,600)
c9.Divide(3,1)
c9.cd(1)
#xresfitvsmaxsip.FitSlicesY()
#xresfitvsmaxsip_2 = r.gDirectory.Get("xresfitvsmaxsip_2")
#xresfitvsmaxsip_2.SetTitle("")
#xresfitvsmaxsip_2.GetYaxis().SetTitleOffset(1.4)
#xresfitvsmaxsip_2.GetYaxis().SetRangeUser(0,2)
#xresfitvsmaxsip_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
#xresfitvsmaxsip_2.GetXaxis().SetTitle("max sip")
#xresfitvsmaxsip_2.Draw("")
xresfitvsmaxsip.Draw("colz")
c9.cd(2)
#yresfitvsmaxsip.FitSlicesY()
#yresfitvsmaxsip_2 = r.gDirectory.Get("yresfitvsmaxsip_2")
#yresfitvsmaxsip_2.SetTitle("")
#yresfitvsmaxsip_2.GetYaxis().SetTitleOffset(1.4)
#yresfitvsmaxsip_2.GetYaxis().SetRangeUser(0,2)
#yresfitvsmaxsip_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
#yresfitvsmaxsip_2.GetXaxis().SetTitle("max sip")
#yresfitvsmaxsip_2.Draw("")
yresfitvsmaxsip.Draw("colz")
c9.cd(3)
#zresfitvsmaxsip.FitSlicesY()
#zresfitvsmaxsip_2 = r.gDirectory.Get("zresfitvsmaxsip_2")
#zresfitvsmaxsip_2.SetTitle("")
#zresfitvsmaxsip_2.GetYaxis().SetTitleOffset(1.4)
#zresfitvsmaxsip_2.GetYaxis().SetRangeUser(0,2)
#zresfitvsmaxsip_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
#zresfitvsmaxsip_2.GetXaxis().SetTitle("max sip")
#zresfitvsmaxsip_2.Draw("")
zresfitvsmaxsip.Draw("colz")
c9.SaveAs("c9.png")

xresfitvsmaxchi2 = r.TH2F("xresfitvsmaxchi2","xresfitvsmaxchi2",20,0,100,100,-2,2)
yresfitvsmaxchi2 = r.TH2F("yresfitvsmaxchi2","yresfitvsmaxchi2",20,0,100,100,-2,2)
zresfitvsmaxchi2 = r.TH2F("zresfitvsmaxchi2","zresfitvsmaxchi2",20,0,100,100,-2,2)
t1.Draw("(vtx_fit_x - vtx_gen_x):(vtx_fit_tkubchi2_max)>>xresfitvsmaxchi2","","goff")
t1.Draw("(vtx_fit_y - vtx_gen_y):(vtx_fit_tkubchi2_max)>>yresfitvsmaxchi2","","goff")
t1.Draw("(vtx_fit_z - vtx_gen_z):(vtx_fit_tkubchi2_max)>>zresfitvsmaxchi2","","goff")
c10 = r.TCanvas("c10","c10",1800,600)
c10.Divide(3,1)
c10.cd(1)
#xresfitvsmaxchi2.FitSlicesY()
#xresfitvsmaxchi2_2 = r.gDirectory.Get("xresfitvsmaxchi2_2")
#xresfitvsmaxchi2_2.SetTitle("")
#xresfitvsmaxchi2_2.GetYaxis().SetTitleOffset(1.4)
#xresfitvsmaxchi2_2.GetYaxis().SetRangeUser(0,2)
#xresfitvsmaxchi2_2.GetYaxis().SetTitle("#sigma_{x} [cm]")
#xresfitvsmaxchi2_2.GetXaxis().SetTitle("max chi2")
#xresfitvsmaxchi2_2.Draw("")
xresfitvsmaxchi2.Draw("colz")
c10.cd(2)
#yresfitvsmaxchi2.FitSlicesY()
#yresfitvsmaxchi2_2 = r.gDirectory.Get("yresfitvsmaxchi2_2")
#yresfitvsmaxchi2_2.SetTitle("")
#yresfitvsmaxchi2_2.GetYaxis().SetTitleOffset(1.4)
#yresfitvsmaxchi2_2.GetYaxis().SetRangeUser(0,2)
#yresfitvsmaxchi2_2.GetYaxis().SetTitle("#sigma_{y} [cm]")
#yresfitvsmaxchi2_2.GetXaxis().SetTitle("max chi2")
#yresfitvsmaxchi2_2.Draw("")
yresfitvsmaxchi2.Draw("colz")
c10.cd(3)
#zresfitvsmaxchi2.FitSlicesY()
#zresfitvsmaxchi2_2 = r.gDirectory.Get("zresfitvsmaxchi2_2")
#zresfitvsmaxchi2_2.SetTitle("")
#zresfitvsmaxchi2_2.GetYaxis().SetTitleOffset(1.4)
#zresfitvsmaxchi2_2.GetYaxis().SetRangeUser(0,2)
#zresfitvsmaxchi2_2.GetYaxis().SetTitle("#sigma_{z} [cm]")
#zresfitvsmaxchi2_2.GetXaxis().SetTitle("max chi2")
#zresfitvsmaxchi2_2.Draw("")
zresfitvsmaxchi2.Draw("colz")
c10.SaveAs("c10.png")
